action.empty.page.name=Empty Page
api.change.document.url=https://developer.huawei.com/consumer/{0}/doc/harmonyos-releases/
api.change.tree.firstlevel.change=:change
export.CSV.file.success=Export CSV file success
export.CSV.file.failed=Export CSV file failed
export.message.success=Succeed to export: {0}
export.message.failed=Failed to export. Error: {0}
scan.failed.message.failed=Failed to export. Error: {0}

api.change.codegenie.prompt=Please help me adapt to an API change. The context information is as follows:\nThe programming language is %s;\nThe SDK version is %s;\nThe affected version is %s;\nThe change location is %s;\nThe relevant API definition is: %s;\nYou can refer to the documentation here: %s;\nPlease generate the refactored ArkTS or C++ code and provide an explanation.
scan.failed.message.scan.failed=API Change Assistant scan failed. Please try again.

toolwindow.stripe.APIChangeAssistant=API Change Assistant

uploadProduct.dialog.title=Upload Product

auto.sign.get.user.team.error=<html>Unable to obtain user group information.<br>Check the following configurations:Network connection,HTTP Proxy,etc.</html>
auto.sign.generate.key.error=Error occurred while generating the key
auto.sign.generate.csr.error=Error Occurred While Generating the CSR
auto.sign.download.cer.error=<html>Failed to download the certificate file. <br>Check the following configurations: Network connection,HTTP Proxy,etc.</html>
auto.sign.download.profile.error=Failed to download the profile, please try again.
auto.sign.add.profile.error=Failed to add the profile, please try again.
auto.sign.parse.profile.error=Failed to parse the profile, please try again.
auto.sign.no.device.error=<html>Unable to create the profile due to a lack of a device. Connect a device via IP or USB first.<br> Skip this step if you are installing a HAP on the emulator.</html>
auto.sign.add.device.error=Failed to add the device, please try again.
auto.sign.read.csrfile.error=Failed to read the .csr file, please try again later
auto.sign.hos.sdkpath.error=<html>Unable to find the SDK that supports API version {0}. Reinstall DevEco Studio and try again.</html>
auto.sign.no.harmony.user.error=The user is not in harmony allow list, please grant the permission
auto.sign.no.download.permission.error=Obtain the Internet (external network) permission before downloading the certificate
auto.sign.certificate.exceed.limit.error=<html>The number of certificates has reached the limit. Delete some certificates and try again.</html>
auto.sign.login.invalidation.error=AccessToken invalid, Please try again after login
auto.sign.login.fail=Failed to log in, please try again. Check the following configurations: Network connection,HTTP Proxy,etc.
auto.sign.file.error=The downloaded .cer or .p7b file is invalid, please try again.
auto.sign.query.agreement.error=<html>Failed to query agreement signing records. <br>The unverified user need to sign the agreement before using automatic signing.</html>
auto.sign.agreement.sign.error=An unverified user need to sign the agreement before using automatic signing.
auto.sign.agreement.scroll.down.label=Please read and accept these terms and conditions. Scroll down for full text:
auto.sign.agreement.button.disagree=Disagree
auto.sign.agreement.button.agree=Agree
auto.sign.login.time.out.msg=login time out
auto.sign.agreement.sign.fail.error=Unable to sign the agreement as an unverified user, Please try again.
auto.sign.device.exceed.limit.error=<html>Device limit reached. Delete some unused devices and try again.</html>
auto.sign.add.device.duplicate.error=Duplicate device name, please try again.
auto.sign.jsPath.error=<html>Failed to identify the router device,please install the JS first,<br>Select File > Settings > OpenHarmony SDK to install JS SDK</html>
auto.sign.jsPath.error.mac=<html>Failed to identify the router device,please install the JS first,<br>Select DevEco Studio > Preferences > OpenHarmony SDK to install JS SDK</html>
auto.sign.test.provision.exceed.limit=<html>Provision number exceeds limit. please click <b>Help > Contact Support</b> for assistance</html>
auto.sign.app.id.invalid=Invalid AppId in the bundle name.
auto.sign.provision.name.repeat=The profile named {0} already exists in the AGC. {1}
auto.sign.agc.provision=Please go to the AGC to delete the profile and try again.
auto.sign.openharmony.sdkpath.error=Failed to obtain the toolchains path,please install the toolchains first, File > Settings > OpenHarmony SDK to install Toolchains on API Version {0}
auto.sign.openharmony.sdkpath.error.mac=Failed to obtain the toolchains path,please install the toolchains first, DevEco Studio > Preferences > OpenHarmony SDK to install Toolchains on API Version {0}
auto.sign.encryption.exist.error=Encryption failed, delete the material folder in the .P12 file directory and use the automatic signature again.

api.change.assistant.csv.output.apiDefinition=Api Definition
api.change.assistant.csv.output.language=Language
api.change.assistant.csv.output.changedInSDK=Changed in SDK
api.change.assistant.csv.output.affectedVersions=Affected Versions
api.change.assistant.csv.output.title=Title
api.change.assistant.csv.output.codeLocation=Code Location
api.change.assistant.csv.output.fixed=Fixed
api.change.assistant.csv.output.changeType=Change Type
api.change.assistant.csv.output.fixed.fixed=Fixed
api.change.assistant.csv.output.fixed.unfixed=Unfixed

api.change.assistant.changeType.visualLayoutChange=UX Visual Layout Change
api.change.assistant.changeType.interactionBehaviorChange=UX Interaction Behavior Change
api.change.assistant.changeType.apiBehaviorChange=API Behavior Change
api.change.assistant.changeType.changesDeletion=Changes Deletion
api.change.assistant.changeType.apiChangeDeprecation=API Change Deprecation
api.change.assistant.changeType.apiDefinitionChange=API Definition Change
